name: gam
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.0.0
  shared_preferences: ^2.1.2
  path_provider: ^2.0.15
  flutter_secure_storage: ^9.0.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.4.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
